name: Package and Deploy to S3 Bucket

on:
  push:
    branches:
      - master

jobs:
  package-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current date and time
        id: unique_datetime
        run: echo "date=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV


      # Step 3: Package the repository into a tar.gz file with date
      - name: Package repository
        run: |
          cd ..
          tar -czf wordpress_${{ env.date }}.tar.gz WordPress/
          echo "Packaged repository into wordpress_${{ env.date }}.tar.gz"

      # Step 4: Configure AWS CLI
      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION

      # Step 5: Upload tar.gz file to S3 bucket
      - name: Upload to S3 Bucket
        run: |
          cd ..
          aws s3 cp wordpress_${{ env.date }}.tar.gz s3://abdallah-wordpress/wordpress_${{ env.date }}.tar.gz
      
      # Step 6: refresh Auto Scaling Group
      - name: Refresh Auto Scaling Group
        run: |
          aws autoscaling start-instance-refresh --auto-scaling-group-name abdallah-lemp-ASG2
